
export const sidebar = [
    {
        title:"dashboard",
        link:"/",
        icon:"/favicon.ico"
    },
    {
        title:"asset",
        link:"/asset",
        icon:"/favicon.ico"
    },
    {
        title:"masters",
        link:"/masters",
        icon:"/favicon.ico"
    },
    {
        title:"accessories",
        link:"/accessories",
        icon:"/favicon.ico"
    },
    {
        title:"licsence",
        link:"/licsence",
        icon:"/favicon.ico"
    },
    {
        title:"components",
        link:"/components",
        icon:"/favicon.ico"
    },
    {
        title:"consumables",
        link:"/consumables",
        icon:"/favicon.ico"
    },
    {
        title:"requestables",
        link:"/requestables",
        icon:"/favicon.ico"
    },
    {
        title:"settings",
        link:"/settings",
        icon:"/favicon.ico"
    },
]